import argparse
parser = argparse.ArgumentParser()
parser.add_argument('integers', metvar='N',type=int,nargs='+')
parser.add_argument('-f','--foo', help='foo bar')
parser.add_argument('-b','--bar',help='bar help')
parser.add_argument('-z', '--zar', help='zar help')
parser.add_argument('-t', '--toggle', action=store_true)
parser.add_argument('-x', '--exclude', action=store_false)
parser.add_argument('-s', '--start', action=store_true)
parser.add_argument('-xx','--kill',help='turn it all off')
args = parser.parse_args()
print(args)